---
- name: Create application group
  ansible.builtin.group:
    name: "{{ app_group }}"
    system: true
    state: present

- name: Create application user
  ansible.builtin.user:
    name: "{{ app_user }}"
    group: "{{ app_group }}"
    home: "{{ app_home }}"
    create_home: false
    shell: /usr/sbin/nologin
    system: true
    state: present

- name: Create application directory
  ansible.builtin.file:
    path: "{{ app_home }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0755"
