---
- name: Restart application
  ansible.builtin.systemd_service:
    name: healthchecks
    daemon_reload: true
    state: restarted

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
